//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NotificationsTemplates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NotificationsTemplates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TemplateApp.Resources.NotificationsTemplates", typeof(NotificationsTemplates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы попросили напомнить вам о задаче &apos;%tasktitle%&apos; &lt;br/&gt;. Срок задачи: %deadline% &lt;br/&gt; Планируемая дата выполнения% %taskplanneddate%
        ///&lt;a href=&apos;%tasklink%&apos;&gt;Ссылка на задачу&lt;/a&gt;.
        /// </summary>
        public static string TaskReminderBodyTemplate {
            get {
                return ResourceManager.GetString("TaskReminderBodyTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Напоминание о задаче &apos;%tasktitle%&apos;.
        /// </summary>
        public static string TaskReminderSubjectTemplate {
            get {
                return ResourceManager.GetString("TaskReminderSubjectTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h2&gt;Добро пожаловать!&lt;/h2&gt;&lt;br&gt;
        ///
        ///Здравствуйте, %username%! &lt;br&gt;
        ///
        ///Поздравляем вас с успешной регистрацией на сайте !&lt;br/&gt;
        ///Для активации вашего аккаунта, пожалуйста &lt;a href=&apos;http://%maindomain%/login?key=%activationkey%&apos;&gt;подтвердите регистрацию&lt;/a&gt; на сайте..
        /// </summary>
        public static string UserRegistrationBodyTemplate {
            get {
                return ResourceManager.GetString("UserRegistrationBodyTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добро пожаловать на сайт!.
        /// </summary>
        public static string UserRegistrationSubjectTemplate {
            get {
                return ResourceManager.GetString("UserRegistrationSubjectTemplate", resourceCulture);
            }
        }
    }
}
